# Generated by Django 6.0.4 on 2026-04-30 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Discord ID')),
                ('discord_username', models.CharField(blank=True, default='', max_length=100, verbose_name='Discord Username')),
                ('discord_global_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Discord Global Name')),
                ('discord_avatar', models.CharField(blank=True, default='', max_length=255, verbose_name='Discord Avatar hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discord_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Дискорд Аккаунт',
                'verbose_name_plural': 'Дискорд Аккаунты',
            },
        ),
    ]
