# Generated by Django 6.0.4 on 2026-04-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Название')),
                ('guild_id', models.IntegerField(verbose_name='ID Discord Channel')),
                ('channel_id', models.IntegerField(verbose_name='ID Discord Channel')),
            ],
            options={
                'verbose_name': 'Discord Channel',
                'verbose_name_plural': 'Discord Channels',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ScheduleGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('archived', models.BooleanField(verbose_name='Архив')),
                ('tags', models.TextField(verbose_name='Тэги')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Расписание игр',
                'verbose_name_plural': 'Расписание игр',
                'ordering': ('created_at',),
            },
        ),
    ]
