# Generated by Django 6.0.4 on 2026-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegame',
            name='discrod_thread_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='ID треда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulegame',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='schedulegame',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Тэги'),
        ),
    ]
