# Generated by Django 6.0.4 on 2026-04-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0002_schedulegame_discrod_thread_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulegame',
            old_name='discrod_thread_id',
            new_name='discord_thread_id',
        ),
    ]
