# Generated by Django 6.0.4 on 2026-04-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0003_rename_discrod_thread_id_schedulegame_discord_thread_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulegame',
            options={'ordering': ('-created_at',), 'verbose_name': 'Расписание игр', 'verbose_name_plural': 'Расписание игр'},
        ),
        migrations.AlterField(
            model_name='discordchannel',
            name='channel_id',
            field=models.BigIntegerField(verbose_name='ID Discord Forum'),
        ),
        migrations.AlterField(
            model_name='discordchannel',
            name='guild_id',
            field=models.BigIntegerField(verbose_name='ID Discord Channel'),
        ),
    ]
