# Generated by Django 6.0.4 on 2026-04-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0004_alter_schedulegame_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Discord User ID')),
                ('name', models.TextField(verbose_name='Имя')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('tentative', 'Tentative'), ('waitlist', 'Waitlist')], max_length=20, verbose_name='Статус')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='lineup.schedulegame')),
            ],
            options={
                'unique_together': {('game', 'discord_user_id', 'name')},
            },
        ),
    ]
