# Generated by Django 6.0.4 on 2026-04-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0005_gameparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCellAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_index', models.IntegerField(verbose_name='Индекс ячейки')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lineup.schedulegame')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lineup.gameparticipant')),
            ],
            options={
                'verbose_name': 'Ячейки',
                'constraints': [models.UniqueConstraint(fields=('game', 'participant'), name='unique_player_per_game'), models.UniqueConstraint(fields=('game', 'cell_index'), name='unique_cell_per_game')],
            },
        ),
    ]
