# Generated by Django 6.0.4 on 2026-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0006_gamecellassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegame',
            name='game_format',
            field=models.CharField(choices=[('20x20', '20x20'), ('26x26', '26x26'), ('30x30', '30x30'), ('48x48', '48x48')], default='20x20', max_length=10, verbose_name='Формат'),
        ),
    ]
