# Generated by Django 6.0.4 on 2026-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineup', '0007_schedulegame_game_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegame',
            name='game_map',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Карта'),
        ),
    ]
